name: Continuous Integration

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  setup:
    runs-on: ubuntu-latest
    outputs:
      cache-key: ${{ steps.cache-keys.outputs.yarn-cache-key }}
    steps:
      - uses: actions/checkout@v2
      
      - id: cache-keys
        run: echo "::set-output name=yarn-cache-key::${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}"

      - name: Cache Node Modules
        uses: actions/cache@v2
        with:
          path: node_modules
          key: ${{ steps.cache-keys.outputs.yarn-cache-key }}

      - name: Install Dependencies
        run: yarn install

  build:
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - uses: actions/checkout@v2

      - name: Use Node Modules Cache
        uses: actions/cache@v2
        with:
          path: node_modules
          key: ${{ needs.setup.outputs.cache-key }}

      - name: Build Project
        run: yarn run build

  prettier:
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - uses: actions/checkout@v2

      - name: Use Node Modules Cache
        uses: actions/cache@v2
        with:
          path: node_modules
          key: ${{ needs.setup.outputs.cache-key }}

      - name: Check Formatting
        run: |
          yarn run prettier
          if [[ -n $(git status -s) ]]; then
            echo "Formatting issues detected"
            exit 1
          fi

  lint:
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - uses: actions/checkout@v2

      - name: Use Node Modules Cache
        uses: actions/cache@v2
        with:
          path: node_modules
          key: ${{ needs.setup.outputs.cache-key }}

      - name: Lint Code
        run: yarn run lint

  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v2

      - name: Use Build Cache
        uses: actions/cache@v2
        with:
          path: |
            node_modules
            dist
          key: ${{ needs.build.outputs.build-cache-key }}

      - name: Run Tests
        run: yarn run test:blocks
